version: '3'

services:
  django:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/store
    ports:
      - 8000:8000
    env_file:
      - ./.env
  db:
    container_name: db
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=nurrulit
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres

volumes:
    postgres_data: