# Generated by Django 4.1.3 on 2022-12-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
