# Generated by Django 4.1.3 on 2022-12-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
